app/config/urls.py
from django.contrib import admin
from django.urls import path,include
from core.webapp.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home),
    path('telefono/',include('core.telefono.urls')),
    path('cliente/',include('core.cliente.urls')),
]

app/core/cliente/urls.py
from django.urls import path
from core.cliente.views import ClienteList,ClienteCreate,ClienteUpdate,ClienteDelete

app_name='cliente'

urlpatterns = [
    path('list/',ClienteList.as_view(),name='listCliente'),
    path('add/',ClienteCreate.as_view(),name='addCliente'),
    path('edit/<str:pk>',ClienteUpdate.as_view(),name='editCliente'),
    path('delete/<str:pk>',ClienteDelete.as_view(),name='deleteCliente'),
]

app/core/telefono/urls.py
from django.urls import path
from core.telefono.views import TipoTelefonoList,TipoTelefonoCreate,TipoTelefonoUpdate,TipoTelefonoDelete,\
    TelefonoList,TelefonoCreate,TelefonoUpdate,TelefonoDelete

app_name='telefono'

urlpatterns = [
    path('tipo/list/',TipoTelefonoList.as_view(),name='listTipoTelefono'),
    path('tipo/add/',TipoTelefonoCreate.as_view(),name='addTipoTelefono'),
    path('tipo/edit/<int:pk>',TipoTelefonoUpdate.as_view(),name='editTipoTelefono'),
    path('tipo/delete/<int:pk>',TipoTelefonoDelete.as_view(),name='deleteTipoTelefono'),
    path('list/<str:pk>',TelefonoList.as_view(),name='listTelefono'),
    path('add/<str:pk>',TelefonoCreate.as_view(),name='addTelefono'),
    path('edit/<int:pk>',TelefonoUpdate.as_view(),name='editTelefono'),
    path('delete/<int:pk>',TelefonoDelete.as_view(),name='deleteTelefono'),
]

app/core/webapp/models.py
from django.db import models

# Create your models here.

app/core/webapp/views.py
from django.shortcuts import render


def home(request):
    return render(request,'index.html')

app/core/webapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

    <head>
        <meta charset="UTF-8">
        <!--<meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        {% block stylesheet %} {% endblock stylesheet %}
        <title class="title-up"> {% block title %} {% endblock title %}</title>
    </head>

    <body>

        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand text-light" href="#">ANÁLISIS II</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link active text-light" aria-current="page" href="/">Inicio</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Administración
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <li><a class="dropdown-item" href="{% url 'cliente:listCliente' %}">Cliente</a></li>
                                    <li><a class="dropdown-item" href="{% url 'telefono:listTipoTelefono' %}">Tipo de teléfono</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <div class="container">
            {% block content %} {% endblock content %}
        </div>
        <footer>
            {% block footer %}{% endblock footer %}
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
        <script>
            {% block scripts %}{% endblock scripts %}
        </script>
    </body>
</html>

app/core/webapp/templates/index.html
{% extends 'base.html' %}
{% block title %} Inicio {% endblock title %}