app/config/urls.py
from django.contrib import admin
from django.urls import path,include
from core.webapp.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home),
    path('telefono/',include('core.telefono.urls')),
    path('cliente/',include('core.cliente.urls')),
]

app/core/cliente/urls.py
from django.urls import path
from core.cliente.views import ClienteList,ClienteCreate,ClienteUpdate,ClienteDelete

app_name='cliente'

urlpatterns = [
    path('list/',ClienteList.as_view(),name='listCliente'),
    path('add/',ClienteCreate.as_view(),name='addCliente'),
    path('edit/<str:pk>',ClienteUpdate.as_view(),name='editCliente'),
    path('delete/<str:pk>',ClienteDelete.as_view(),name='deleteCliente'),
]

app/core/telefono/urls.py
from django.urls import path
from core.telefono.views import TipoTelefonoList,TipoTelefonoCreate,TipoTelefonoUpdate,TipoTelefonoDelete,\
    TelefonoList,TelefonoCreate,TelefonoUpdate,TelefonoDelete

app_name='telefono'

urlpatterns = [
    path('tipo/list/',TipoTelefonoList.as_view(),name='listTipoTelefono'),
    path('tipo/add/',TipoTelefonoCreate.as_view(),name='addTipoTelefono'),
    path('tipo/edit/<int:pk>',TipoTelefonoUpdate.as_view(),name='editTipoTelefono'),
    path('tipo/delete/<int:pk>',TipoTelefonoDelete.as_view(),name='deleteTipoTelefono'),
    path('list/<str:pk>',TelefonoList.as_view(),name='listTelefono'),
    path('add/<str:pk>',TelefonoCreate.as_view(),name='addTelefono'),
    path('edit/<int:pk>',TelefonoUpdate.as_view(),name='editTelefono'),
    path('delete/<int:pk>',TelefonoDelete.as_view(),name='deleteTelefono'),
]

app/core/cliente/models.py
from django.db import models
from core.persona.models import Persona


class Cliente(Persona):
    '''
    Campos para el modelo Cliente
    '''
    nit_cliente = models.CharField(verbose_name='Nit',primary_key=True,max_length=10)
    favorito = models.BooleanField(verbose_name='Favorito',default=False)

    '''
    Funcion para la devolución del objeto Cliente
    '''
    def __str__(self):
        return f'{self.nit_cliente} - {self.nombre} {self.apellido}'

    '''
    Configuraciones de la clase Meta
    '''
    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

app/core/cliente/forms.py
from django import forms
from core.cliente.models import Cliente


class FormCliente(forms.ModelForm):

    class Meta:
        model = Cliente
        fields = [
            'nit_cliente',
            'favorito',
            'nombre',
            'apellido',
            'genero',
            'fecha_nacimiento',
            'correo',
        ]
        labels = {
            'nit_cliente':'Nit',
            'favorito':'Favorito',
            'nombre':'Nombre',
            'apellido':'Apellido',
            'genero':'Género',
            'fecha_nacimiento':'Fecha de nacimiento',
            'correo':'Correo',
        }
        widgets = {
            'nit_cliente':forms.TextInput(),
            'favorito':forms.CheckboxInput(),
            'nombre':forms.TextInput(),
            'apellido':forms.TextInput(),
            'genero':forms.CheckboxInput(),
            'fecha_nacimiento':forms.DateInput(),
            'correo':forms.EmailInput(),
        }

app/core/cliente/views.py
from django.views.generic import CreateView,ListView,UpdateView,DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render,get_object_or_404
from django.urls import reverse_lazy
from core.cliente.models import Cliente
from core.cliente.forms import FormCliente


class ClienteList(ListView):
    model = Cliente
    template_name = 'list_cliente.html'


class ClienteCreate(SuccessMessageMixin,CreateView):
    model = Cliente
    form_class = FormCliente
    template_name = 'add_cliente.html'
    success_url = reverse_lazy('cliente:addCliente')
    success_message = 'Ingresado con éxito...'

    def post(self, request, *args, **kwargs):
        cliente = Cliente()
        cliente.nit_cliente = request.POST.get('nit_cliente')
        cliente.nombre = request.POST.get('nombre')
        cliente.apellido = request.POST.get('apellido')
        cliente.fecha_nacimiento = request.POST.get('fecha_nacimiento')
        cliente.correo = request.POST.get('correo')
        fav = request.POST.get('favorito')
        if fav == 'on':
            cliente.favorito = True
        else:
            cliente.favorito = False
        cliente.genero = request.POST.get('genero')
        cliente.save()
        return render(request,self.template_name, {'msn':'success','clienteNuevo':cliente.nit_cliente})


class ClienteUpdate(SuccessMessageMixin,UpdateView):
    model = Cliente
    form_class = FormCliente
    template_name = 'edit_cliente.html'
    success_url = reverse_lazy('cliente:listCliente')
    success_message = 'Modificado con éxito...'

    def get(self, request, *args, **kwargs):
        id = self.kwargs.get('pk')
        cliente = get_object_or_404(Cliente,pk=id)
        return render(request,self.template_name,{'cliente':cliente})


class ClienteDelete(SuccessMessageMixin,DeleteView):
    model = Cliente
    template_name = 'delete_cliente.html'
    success_url = reverse_lazy('cliente:listCliente')
    success_message = 'Eliminado con éxito...'

    def get(self, request, *args, **kwargs):
        id = self.kwargs.get('pk')
        cliente = get_object_or_404(Cliente,pk=id)
        return render(request,self.template_name,{'cliente':cliente})

app/core/cliente/templates/add_cliente.html
{% extends 'base.html' %}
{% block title %} Cliente - Add {% endblock title %}

{% block content %}
<div class="row align-items-center justify-content-start col-13">
    <h1 class="">Cliente</h1>
</div>
<div class="form-group">
    {% csrf_token %}
    {% if messages %}
        {% for msn in messages%}
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
            </symbol>
        </svg>
        <div class="alert alert-success d-flex align-items-center col-13" role="alert">
            <svg class="bi flex-shrink-0 me-2 col-1" width="24" height="24" role="img" aria-label="Success:">
                <use xlink:href="#check-circle-fill"/>
            </svg>
            <div class="col-10">
                {{msn}}
            </div>
            <div class="col-1">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
        </div>
        {% endfor %}
    {% endif %}
</div>
<form method="POST">
    {% csrf_token %}
    <div class="form-group mb-3">
        <input type="text" class="form-control" name="nit_cliente" placeholder="Nit">
    </div>
    <div class="form-group mb-3">
        <input type="text" class="form-control" name="nombre" placeholder="Nombre">
    </div>
    <div class="form-group mb-3">
        <input type="text" class="form-control" name="apellido" placeholder="Apellido">
    </div>
    <div class="form-group mb-3">
        <label for="h">Hombre</label>
        <input id="h" type="radio" class="" name="genero" value="H">
        <label for="m">Mujer</label>
        <input id="m" type="radio" class="" name="genero" value="M">

    </div>
    <div class="form-group mb-3">
        <input id="favorito" type="checkbox" class="" name="favorito">
        <label for="favorito">Favorito</label>
    </div>
    <div class="form-group mb-3">
        <input type="date" class="form-control" name="fecha_nacimiento">
    </div>
    <div class="form-group mb-3">
        <input type="email" class="form-control" name="correo" placeholder="Correo">
    </div>
    <div class="row justify-content-center col-13">
        <div class="row justify-content-between mt-3">
            <button id="guardar" type="submit" class="btn btn-outline-success col-md-3 mb-2">Guardar</button>
            {% if clienteNuevo %}
            <a id="telefono" class="btn btn-outline-primary col-md-3 mb-2" href="{% url 'telefono:addTelefono' clienteNuevo %}">Agregar teléfono</a>
            {% endif %}
            <a id="listar" class="btn btn-outline-primary col-md-3 mb-2" href="{% url 'cliente:listCliente' %}">Lista</a>
        </div>
    </div>
</form>
{% endblock content %}

app/core/cliente/templates/delete_cliente.html
{% extends 'base.html' %}
{% block title %} Cliente - Delete {% endblock title %}
{% block content %}
<div class="container mt-5">
<form method="POST">
    {% csrf_token %}
    <div class="row justify-content-center pt-5">
        <h2 class="row justify-content-center align-items-center pb-4">¿Desea eliminar el cliente {{cliente.nit_cliente}} - {{cliente.nombre}} {{cliente.apellido}}?</h2>
        <div class="row justify-content-between col-5">
            <button type="submit" class="btn btn-danger col-md-5">Sí</button>
            <a href="{% url 'cliente:listCliente' %}" class="btn btn-primary col-md-5">Cancelar</a>
        </div>
    </div>
</form>
</div>
{% endblock content %}

app/core/cliente/templates/list_cliente.html
{% extends 'base.html' %}
{% block title %}Cliente - List{% endblock title %}
{% block content %}
<h1 class="row align-items-center justify-content-center">CLIENTES</h1>
<div class="row col-12 justify-content-end mb-2">
        <a class="btn btn-outline-primary col-md-2" href="{% url 'cliente:addCliente' %}">AGREGAR</a>
</div>
<table class="table">
    <thead class="table-dark">
        <tr>
            <th>NIT</th>
            <th>NOMBRE</th>
            <th>APELLIDO</th>
            <th>GÉNERO</th>
            <th>EDAD</th>
            <th>CORREO</th>
            <th>FAVORITO</th>
            <th>TELEFONOS</th>
            <th>EDITAR</th>
            <th>ELIMINAR</th>
        </tr>
    </thead>
    <tbody>
        {% for cliente in object_list %}
        <tr>
            <td>{{cliente.nit_cliente}}</td>
            <td>{{cliente.nombre}}</td>
            <td>{{cliente.apellido}}</td>
            <td>{{cliente.genero}}</td>
            <td>{{cliente.edad}}</td>
            <td>{{cliente.correo}}</td>
            {% if cliente.favorito %}
            <td><input type="checkbox" checked disabled></td>
            {% endif %}
            <td>
                <a href="{% url 'telefono:listTelefono' cliente.nit_cliente %}" class="btn btn-ms btn-outline-primary">ver</a>
            </td>
            <td>
                <a href="{% url 'cliente:editCliente' cliente.nit_cliente %}" class="btn btn-ms btn-outline-success">O</a>
            </td>
            <td>
                <a href="{% url 'cliente:deleteCliente' cliente.nit_cliente %}" class="btn btn-ms btn-outline-danger">X</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}