app/config/urls.py
from django.contrib import admin
from django.urls import path,include
from core.webapp.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home),
    path('telefono/',include('core.telefono.urls')),
    path('cliente/',include('core.cliente.urls')),
]

app/core/telefono/urls.py
from django.urls import path
from core.telefono.views import TipoTelefonoList,TipoTelefonoCreate,TipoTelefonoUpdate,TipoTelefonoDelete,\
    TelefonoList,TelefonoCreate,TelefonoUpdate,TelefonoDelete

app_name='telefono'

urlpatterns = [
    path('tipo/list/',TipoTelefonoList.as_view(),name='listTipoTelefono'),
    path('tipo/add/',TipoTelefonoCreate.as_view(),name='addTipoTelefono'),
    path('tipo/edit/<int:pk>',TipoTelefonoUpdate.as_view(),name='editTipoTelefono'),
    path('tipo/delete/<int:pk>',TipoTelefonoDelete.as_view(),name='deleteTipoTelefono'),
    path('list/<str:pk>',TelefonoList.as_view(),name='listTelefono'),
    path('add/<str:pk>',TelefonoCreate.as_view(),name='addTelefono'),
    path('edit/<int:pk>',TelefonoUpdate.as_view(),name='editTelefono'),
    path('delete/<int:pk>',TelefonoDelete.as_view(),name='deleteTelefono'),
]

app/core/telefono/models.py
from django.db import models
from core.cliente.models import Cliente


class TipoTelefono(models.Model):
    '''
    Campos para el modelo TipoTelefono
    '''
    id_tipo_telefono = models.AutoField(primary_key=True)
    tipo = models.CharField(verbose_name='Tipo de telefono',max_length=20)

    '''
    Método str para devolución de objeto
    '''
    def __str__(self):
        return f'{self.tipo}'

    '''
    Configuraciones para la clase Meta
    '''
    class Meta:
        verbose_name = 'Tipo de teléfono'
        verbose_name = 'Tipos de teléfono'


class Telefono(models.Model):
    '''
    Campos para el modelo Telefono
    '''
    num_telefono = models.PositiveIntegerField(verbose_name='Número de teléfono',primary_key=True)
    predeterminado = models.BooleanField(verbose_name='Predeterminado',default=False)
    tipo = models.ForeignKey(TipoTelefono,verbose_name='Tipo',on_delete=models.SET_NULL, blank=True,null=True)
    cliente = models.ForeignKey(Cliente, verbose_name='Cliente', on_delete=models.CASCADE)

    '''
    Método str para devolución de objeto
    '''
    def __str__(self):
        predeterminado = ''
        if self.predeterminado:
            predeterminado = 'Predeterminado'
        return f'{self.num_telefono} - {predeterminado}'

    '''
    Configuraciones para la clase Meta
    '''
    class Meta:
        verbose_name = 'Teléfono'
        verbose_name_plural = 'Telefonos'

app/core/telefono/forms.py
from django import forms
from core.telefono.models import TipoTelefono,Telefono


'''
Formulario para Tipo de Teléfono
'''
class FormTipoTelefono(forms.ModelForm):

    class Meta:
        model = TipoTelefono
        fields = [
            'tipo',
        ]
        labels = {
            'tipo':'Tipo de teléfono',
        }
        widgets = {
            'tipo':forms.TextInput(),
        }


'''
Formulario para Telefono
'''
class FormTelefono(forms.ModelForm):

    class Meta:
        model = Telefono
        fields = [
            'num_telefono',
            'predeterminado',
            'tipo',
            'cliente',
        ]
        labels = {
            'num_telefono':'Número de teléfono',
            'predeterminado':'Predeterminado',
            'tipo':'Tipo de teléfono',
            'cliente':'Cliente',
        }
        widgets = {
            'num_telefono':forms.NumberInput(),
            'predeterminado':forms.CheckboxInput(),
            'tipo':forms.Select(),
            'cliente':forms.Select(),
        }

app/core/telefono/views.py
from django.views.generic import CreateView,ListView,UpdateView,DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render,get_object_or_404
from django.urls import reverse_lazy
from core.telefono.models import TipoTelefono,Telefono
from core.telefono.forms import FormTipoTelefono,FormTelefono
from core.cliente.models import Cliente


'''
VISTAS PARA TIPO TELEFONO
'''
class TipoTelefonoList(ListView):
    model = TipoTelefono
    template_name = 'tipo_telefono/list_tipo_telefono.html'


class TipoTelefonoCreate(SuccessMessageMixin,CreateView):
    model = TipoTelefono
    form_class = FormTipoTelefono
    template_name = 'tipo_telefono/add_tipo_telefono.html'
    success_url = reverse_lazy('telefono:addTipoTelefono')
    success_message = 'Ingresado con éxito...'


class TipoTelefonoUpdate(SuccessMessageMixin,UpdateView):
    model = TipoTelefono
    form_class = FormTipoTelefono
    template_name = 'tipo_telefono/edit_tipo_telefono.html'
    success_url =  reverse_lazy('telefono:listTipoTelefono')
    success_message = 'Modificado con éxito...'

    def get(self, request, *args, **kwargs):
        id = self.kwargs.get('pk')
        tipo = get_object_or_404(TipoTelefono,pk=id)
        return render(request,self.template_name,{'tipo':tipo})


class TipoTelefonoDelete(SuccessMessageMixin,DeleteView):
    model = TipoTelefono
    template_name = 'tipo_telefono/delete_tipo_telefono.html'
    success_url = reverse_lazy('telefono:listTipoTelefono')
    success_message = 'Eliminado con éxito...'

    def get(self, request, *args, **kwargs):
        id = self.kwargs.get('pk')
        tipo = get_object_or_404(TipoTelefono,pk=id)
        return render(request,self.template_name,{'tipo':tipo})



'''
VISTAS PARA TELEFONO
'''
class TelefonoList(ListView):
    model = Telefono
    template_name = 'telefono/list_telefono.html'

    def get(self, request, *args, **kwargs):
        nit = self.kwargs.get('pk')
        telefonos = []
        tels = Telefono.objects.all()
        for tel in tels:
            if tel.cliente.nit_cliente == nit:
                telefonos.append(tel)
        return render(request, self.template_name,{'telefonos':telefonos,'nit':nit})

class TelefonoCreate(SuccessMessageMixin,CreateView):
    model = Telefono
    form_class = FormTelefono
    template_name = 'telefono/add_telefono.html'
    success_url = reverse_lazy('cliente:listCliente')
    success_message = 'Ingresado con éxito...'

    def get(self, request, *args, **kwargs):
        tipos = TipoTelefono.objects.all()
        nit = self.kwargs.get('pk')
        return render(request,self.template_name,{'tipos':tipos,'nit':nit})



class TelefonoUpdate(SuccessMessageMixin,UpdateView):
    model = Telefono
    form_class = FormTelefono
    template_name = 'telefono/edit_telefono.html'
    success_url =  reverse_lazy('cliente:listCliente')
    success_message = 'Modificado con éxito...'

    def get(self, request, *args, **kwargs):
        id = self.kwargs.get('pk')
        telefono = get_object_or_404(Telefono,pk=id)
        return render(request,self.template_name,{'telefono':telefono})


class TelefonoDelete(SuccessMessageMixin,DeleteView):
    model = Telefono
    template_name = 'telefono/delete_telefono.html'
    success_url = reverse_lazy('cliente:listCliente')
    success_message = 'Eliminado con éxito...'

    def get(self, request, *args, **kwargs):
        id = self.kwargs.get('pk')
        telefono = get_object_or_404(Telefono,pk=id)
        return render(request,self.template_name,{'telefono':telefono})

app/core/telefono/templates/tipo_telefono/add_tipo_telefono.html
{% extends 'base.html' %}
{% block title %} Tipo de teléfono - Add {% endblock title %}

{% block content %}
<div class="row align-items-center justify-content-start col-13">
    <h1 class="">Tipo de telefono</h1>
</div>
<div class="form-group">
    {% csrf_token %}
    {% if messages %}
        {% for msn in messages%}
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
            </symbol>
        </svg>
        <div class="alert alert-success d-flex align-items-center col-13" role="alert">
            <svg class="bi flex-shrink-0 me-2 col-1" width="24" height="24" role="img" aria-label="Success:">
                <use xlink:href="#check-circle-fill"/>
            </svg>
            <div class="col-10">
                {{msn}}
            </div>
            <div class="col-1">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
        </div>
        {% endfor %}
    {% endif %}
</div>
<form method="POST">
    {% csrf_token %}
    <div class="form-group mb-3">
        <input type="text" class="form-control" name="tipo" placeholder="Tipo de telefono">
    </div>
    <div class="row justify-content-center col-13">
        <div class="row justify-content-between mt-3">
            <button id="guardar" type="submit" class="btn btn-outline-success col-md-3 mb-2">Guardar</button>
            <a id="listar" class="btn btn-outline-primary col-md-3 mb-2" href="{% url 'telefono:listTipoTelefono' %}">Lista</a>
        </div>
    </div>
</form>
{% endblock content %}

app/core/telefono/templates/tipo_telefono/delete_tipo_telefono.html
{% extends 'base.html' %}
{% block title %} Tipo de teléfono - Delete {% endblock title %}
{% block content %}
<div class="container mt-5">
<form method="POST">
    {% csrf_token %}
    <div class="row justify-content-center pt-5">
        <h2 class="row justify-content-center align-items-center pb-4">¿Desea eliminar el tipo de telefono {{tipo.id_tipo_telefono}} - {{tipo.tipo}}?</h2>
        <div class="row justify-content-between col-5">
            <button type="submit" class="btn btn-danger col-md-5">Sí</button>
            <a href="{% url 'telefono:listTipoTelefono' %}" class="btn btn-primary col-md-5">Cancelar</a>
        </div>
    </div>
</form>
</div>
{% endblock content %}

app/core/telefono/templates/tipo_telefono/edit_tipo_telefono.html
{% extends 'base.html' %}
{% block title %} Tipo de Teléfono - Edit {% endblock title %}

{% block content %}
<div class="row align-items-center justify-content-start col-13">
    <h1 class="">Tipo de telefono</h1>
</div>
<div class="form-group">
    {% csrf_token %}
    {% if messages %}
        {% for msn in messages%}
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
            </symbol>
        </svg>
        <div class="alert alert-success d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:">
                <use xlink:href="#check-circle-fill"/>
            </svg>
            <div>
                {{msn}}
            </div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">X</button>
        </div>
        {% endfor %}
    {% endif %}
    </div>
<form method="POST">
    {% csrf_token %}
    <div class="form-group mb-3">
        <input type="text" class="form-control" name="tipo" placeholder="Tipo de telefono" value="{{tipo.tipo}}">
    </div>
    <div class="row justify-content-center col-13">
        <div class="row justify-content-between mt-3">
            <button id="guardar" type="submit" class="btn btn-outline-success col-md-3 mb-2">Guardar</button>
            <a id="listar" class="btn btn-outline-primary col-md-3 mb-2" href="{% url 'telefono:listTipoTelefono' %}">Lista</a>
        </div>
    </div>
</form>
{% endblock content %}

app/core/telefono/templates/tipo_telefono/list_tipo_telefono.html
{% extends 'base.html' %}
{% block title %}Tipo Telefono - List{% endblock title %}
{% block content %}
<h1 class="row align-items-center justify-content-center">TIPOS DE TELEFONO</h1>
<div class="row col-12 justify-content-end mb-2">
        <a class="btn btn-outline-primary col-md-2" href="{% url 'telefono:addTipoTelefono' %}">AGREGAR</a>
</div>
<table class="table">
    <thead class="table-dark">
        <tr>
            <th>ID</th>
            <th>TIPO DE TELEFONO</th>
            <th>EDITAR</th>
            <th>ELIMINAR</th>
        </tr>
    </thead>
    <tbody>
        {% for tipo in object_list %}
        <tr>
            <td>{{tipo.id_tipo_telefono}}</td>
            <td>{{tipo.tipo}}</td>
            <td>
                <a href="{% url 'telefono:editTipoTelefono' tipo.id_tipo_telefono %}" class="btn btn-ms btn-outline-success">O</a>
            </td>
            <td>
                <a href="{% url 'telefono:deleteTipoTelefono' tipo.id_tipo_telefono %}" class="btn btn-ms btn-outline-danger">X</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}